config/routes.rb
TaggdIt::Application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
              controllers: { omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en/ do
    resources :profile
    resources :comments
    resources :images do
      member { post :vote }
    end

    match '/about',       to: 'static_pages#about',     via: :get
    match '/policy',      to: 'static_pages#policy',    via: :get
  end
  root 'images#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image, dependent: :destroy
  belongs_to :user,  dependent: :destroy
  self.per_page = 10
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def show
    @user = User.find(@comment.user_id)
  end

  def index
    @comments = Comment.order('created_at DESC')
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def update
  end

  def destroy
    @image = Image.find(@comment.image_id)
    @comment.destroy
    flash[:notice] = "Comment Destroyed."
    redirect_to @image
  end

  def create
    @comment = Comment.new(comment_params)
    @image = Image.find(@comment.image_id)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @image,
                    notice: 'Comment created!'}
        format.json { render json: @image,
                    notice: 'Comment created!'}
      else
        format.html { render @image }
        format.json { render json: @comment.errors }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body,
                  :user_id, :image_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <ul>
    <li><%= comment.body %></li>
    <li> By: <%= link_to @user.name, profile_path(@user) %> </li>

    <% if current_user.id == comment.user_id || current_user.admin? %>
      <li><%= button_to 'Edit', edit_comment_path(comment) %></li>
      <li><%= button_to 'Delete', comment_path(comment), method: :delete %></li>
    <% end %>
  </ul>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "comment") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Comment Here:" %>
    <%= f.text_field :body %>
  </div>

  <%= f.hidden_field :image_id, value: @image.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= f.submit "Submit a Comment" %>
  </div>
<% end %>

app/views/comments/_show_comments.html.erb
<ul>
  <% if @comments.present? %>
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  <% end %>
</ul>