config/routes.rb
TaggdIt::Application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
              controllers: { omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en/ do
    resources :profile
    resources :comments
    resources :images do
      member { post :vote }
    end

    match '/about',       to: 'static_pages#about',     via: :get
    match '/policy',      to: 'static_pages#policy',    via: :get
  end
  root 'images#index'
end

app/views/layouts/modals/_signin.html.erb
<div class="modal-signin-box">
  <h2>Sign in</h2>

  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <div><%= f.label :email %><br />
    <%= f.email_field :email, class: "form-control", :autofocus => true %></div>

    <div><%= f.label :password %><br />
    <%= f.password_field :password, class: "form-control" %></div>

    <% if devise_mapping.rememberable? -%>
      <div class="checkbox"><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
    <% end %>


    <div><%= f.submit "Sign in", class: "btn-custom btn btn-large btn-block" %></div>
  <% end %>

  <%= render "devise/shared/links" %>
  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end -%>
</div>

app/views/layouts/modals/_signup.html.erb
<div class="modal-signup-box">
  <h2>Sign up</h2>

    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>

    <div><%= f.label :username %><br />
    <%= f.text_field :username %></div>

    <div><%= f.label :email %><br />
    <%= f.email_field :email, class: "form-control", :autofocus => true %></div>

    <div><%= f.label :password %><br />
    <%= f.password_field :password, class: "form-control" %></div>

    <div><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, class: "form-control" %></div>

    </br>

    <div><%= f.submit "Join us!", class: "btn-custom btn btn-large btn-block" %></div>
    <% end %>
  <%= render "devise/shared/links" %>
</div>

app/views/layouts/modals/_uploader.html.erb
<% if current_user %>
  <% if @image != nil %>
    <%= render 'form' %>
  <% end %>
<% else %>
    <%= render 'layouts/modals/signup' %>
<% end %>