config/routes.rb
TaggdIt::Application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
              controllers: { omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en/ do
    resources :profile
    resources :comments
    resources :images do
      member { post :vote }
    end

    match '/about',       to: 'static_pages#about',     via: :get
    match '/policy',      to: 'static_pages#policy',    via: :get
  end
  root 'images#index'
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :location, presence: true
  mount_uploader :name, ImageUploader
  geocoded_by :location
  after_validation :geocode

  has_reputation :votes, :source => :user,
    :source_of => { :reputation => :karma,
                    :of => :user }

  def uploaded_by?(user)
    user_id == user.id
  end
  self.per_page = 15

# This is a console-use command to change S3 if image
# versions are modified within ImageUploader.

  def self.recreate_all_versions!
    self.all.each do |image|
      # image.process_your_uploader_upload = true (if using carrierwave_backgrounder)
      image.name.cache_stored_file!
      image.name.retrieve_from_cache!(image.name.cache_name)
      image.name.recreate_versions!
      image.save!
    end
  end

  def short_name
    self.name.to_s.split('/')[-1].split('.')[0].camelize
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index]

  def vote
    value = params[:type] == "up" ? 1 : -1
    @image = Image.find(params[:id])
    @image.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back
  end

  def index
    ordering = params[:order] || 'new'
    case ordering
      when 'hot' then @images = sort_by_votes
      when 'new' then @images = sort_by_newest
    end
    @image  = Image.new
  end

  def show
    @user = User.find(@image.user_id)
    @comment = Comment.new
    @comments = @image.comments
  end


  def new
    @image = Image.new
  end

  def edit
  end

  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_path , notice: 'Image was successfully created.' }
        format.js
      else
        format.html { render action: 'new' }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
        format.js { render :js => "window.location.href =('#{image_path(@image)}');"}
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(current_user), notice: 'Image was successfully destroyed.'}
      format.json { head :no_content }
      format.js
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def image_params
    params.require(:image).permit(:name, :location, :user_id, :image)
  end

  def sort_by_votes
    image_ids = ActiveRecord::Base.connection.execute("SELECT target_id FROM rs_reputations WHERE target_type = 'Image' ORDER BY value DESC")
    @images = []
    image_ids = image_ids.map { |item| item["target_id"].to_i }
    image_ids.each { |id| @images << Image.find(id) }
    @images.paginate(page: params[:page])
  end

  def sort_by_newest
    @images = Image.order("created_at DESC").paginate(page: params[:page])
  end
end

app/views/images/_form.html.erb
<%= form_for(@image, remote: :ajaxed, :html => {:multipart => true}, :authenticity_token => true) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location, :placeholder => "City, Street, Zipcode, or Lat/Longitute" %>
  </div>

    <div class="field">
      <%= f.file_field :name %>
    </div>

    <div><p><%= @image.name %></p></div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= f.submit "Upload Image", class: "btn-custom btn-large ajax-upload" %>
  </div>
<% end %>

app/views/images/_image.html.erb
  <ul class="thumb-frame">
  <li class="inside-pic" id="<%= dom_id(image) %>"><%= link_to image_tag(image.name_url(:indexed).to_s), image_path(image) %></li>
  <li class="thumb-votes"><%= pluralize image.reputation_for(:votes).to_i, "vote" %></li>
  <li class="thumb-cast-vote">
    <%= link_to "", vote_image_path(image, type: "up"), class: "icon-large icon-thumbs-up", method: :post %> ||
    <%= link_to "", vote_image_path(image, type: "down"), class: "icon-large icon-thumbs-down", method: :post %>
  </li>


  <li class="thumb-location"><%= image.location %></li>
  <li class="thumb-uploaded"><%= distance_of_time_in_words(image.created_at, Time.current) %> Ago</li>

  <% if current_user && current_user.admin? %>
    <li class="thumb-details"><%= link_to 'Edit', edit_image_path(image), class: "btn-custom btn-small" %></li>
    <li class="thumb-details"><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-custom btn-small" %></li>
  <% end %>
 </li>
</ul>

app/views/images/create.js.erb
$(.uploader).fadeIn()
$(.inside-pic:last).after('<%= j render(@images) %>')

app/views/images/edit.html.erb
<div class="new_image_box edit_image_box">
  <h1>Edit your Image</h1>
  <% if @image.user_id == current_user.id %>
    <%= render partial: 'form', locals: { :ajaxed => false } %>
  <% end %>
  <%= link_to 'Back to All Pictures', images_path %>
</div>

app/views/images/index.html.erb
<div class="banner">
  <div class="images-title pull-left">
    <h2>Newest Uploads</h2>
    <h3> From around the World </h3>
  </div>
  <div class="upload-button pull-right">
    <h4> Or upload your own </h4>
    <br/>
    <%= link_to 'Upload', "#uploadModal", class: "btn-large btn-custom uploader", 'data-toggle' => 'modal' %>
  </div>
</div>

<div class="custom-container">
  <div class="all-images">
    <%= render @images %>
    <%= will_paginate @images %>
  </div>
</div>

app/views/images/new.html.erb
<div class="new_image_box">
  <h1>Upload a Picture</h1>
  <% if current_user %>
    <%= render partial: 'form', locals: { :ajaxed => true } %>
  <% end %>
  <%= link_to 'Back to All Pictures', images_path %>
</div>

app/views/images/new.js.erb
$('.uploader').hide()
$('.uploader').after('<%= j render("form") %>')

$(document).ajaxError(function (e, xhr, settings) {
        if (xhr.status == 401) {
           window.location.replace(this)
        }
    });

app/views/images/show.html.erb
<div class="show">
  <ul class="show-uploads">
    <div class="show-pics">
      <h1> Check out this Image </h1>
      <h3> <%= @image.short_name %> </h3>
      <li><%= image_tag @image.name_url(:large).to_s %></li>
      <br />
      <li><%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@image.latitude}%2C#{@image.longitude}&zoom=18&size=800x400&maptype=hybrid&sensor=true" %></li>
    </div>
    <div class="show-info">
      <li><h4> Vote? </h4></li>
      <li>
        <%= link_to "up", vote_image_path(@image, type: "up"), method: :post %> ||
        <%= link_to "down", vote_image_path(@image, type: "down"), method: :post %>
      </li>
      <li> (<%= @image.reputation_for(:votes).to_i %> Votes) </li>
      <li><h3>Location:</h3></li>
      <li><h4><%= @image.location %></h4></li>

      <li><h3>Uploaded:</h3></li>
      <li><%= distance_of_time_in_words(@image.created_at, Time.current) %> Ago</li>
      <li>(<%= l @image.created_at, :format => :short %>)</li>

      <li><h4>Uploaded By:</h4></li>
      <li><%=link_to "#{@user.username}", profile_path(@user) %></li><br/>

      <% if @image.user_id == current_user.id %>
        <%= link_to 'Edit your Picture', edit_image_path(@image) %>
      <% end %>

      <% if current_user.present? %>
        <%= render 'comments/form' %>
      <% end %>

      <%= render 'comments/show_comments' %>

      <%= link_to 'Back to all Images', images_path %>
    </div>
  </ul>
</div>