config/routes.rb
TaggdIt::Application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
              controllers: { omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en/ do
    resources :profile
    resources :comments
    resources :images do
      member { post :vote }
    end

    match '/about',       to: 'static_pages#about',     via: :get
    match '/policy',      to: 'static_pages#policy',    via: :get
  end
  root 'images#index'
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">&copy; 2013</div>
      <div class="col-md-4">
        <ul class="nav nav-pills">
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Github", "https://github.com/rjswenson/Taggd.it" %></li>
          <li><%= link_to "Policy", policy_path %></li>
        </ul>
      </div>
      <div class="col-md-4">
        <h4 class="text-right">Copyright 2013</h4>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="js-clingify-placeholder" style="height: 61px;">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container top-zone">
      <ul class="nav navbar-nav">
        <li><%= image_tag('https://s3-us-west-2.amazonaws.com/assets.taggd/taggdit.jpg', width: 200, width: 90) %></li>
        <li><%= link_to "Home", root_path, class: "menu-item" %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle = "dropdown">Pictures <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Recent Uploads", images_path(:order => 'new') %></li>
            <li><%= link_to "Top Sprays", images_path(:order => 'hot') %></li>
            <li><%= link_to "Upload!", new_image_path %></li>
          </ul>
        </li>

        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle = "dropdown"><%= current_user.username %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", profile_path(current_user) %></li>
              <li><%= link_to "Edit", edit_user_registration_path(current_user) %></li>
              <li role="presentation" class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "signout", data: {toggle: "modal"} %></li>
            </ul>
          </li>
        <% else %>
          <!-- Button trigger modal -->

          <li><%= link_to "Sign In", "#signinModal", "data-toggle" => "modal" %></li>
          <li><%= link_to "Create Account", "#signupModal", "data-toggle" => "modal" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/_welcome.html.erb
<div class="welcome">
  <p>Welcome To Taggd.it
Explore and Find Graffiti Locations

and Upload it!.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taggd.it</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Graffiti sharing">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'https://s3-us-west-2.amazonaws.com/assets.taggd/favicon.ico' %>
  <%= render 'layouts/shim' %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45881425-1', 'taggd.it');
  ga('send', 'pageview');

</script>
</head>

<body>
  <%= render 'layouts/header' %>

<!-- Modal -->
<div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-text">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <%= render "layouts/modals/signin" %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <%= render "layouts/modals/signup" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <%= render "layouts/modals/uploader" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
        <%= value %>
    </div>
<% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>